name: Build
on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ["client", "api", "flow-metrics"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --filter ${{ matrix.app }}
      - run: pnpm lint --filter ${{ matrix.app }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ["client", "api", "flow-metrics"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --filter ${{ matrix.app }}
      - run: pnpm build --filter ${{ matrix.app }}
      - run: pnpm test --filter ${{ matrix.app }}

  test-e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm test:e2e
